### ISSUE TITLE
转换错误.

### ISSUE THREAD

**Issue by q2333gh** [EXKulo/xmind_markdown_converter#4]
操作系统:WSL Ubuntu
.xmind文件是 xmind11 版本打开的

提示
![image](https://github.com/EXKulo/xmind_markdown_converter/assets/32679742/dbb3f6c1-f820-40d1-8326-cf2c1ec0eff2)

**Comment by nanqic** [comment]
不太行。转换的格式乱了。不如哪个8年前的node版

**Comment by q2333gh** [comment]
官方不对api和sdk做支持的. 或者是有官方那个.但是几乎没啥用

**Comment by nicekate** [comment]
操作系统mac
同样生成的md文件内容：

Warning
警告
Attention
Warnung
경고

- This file can not be opened normally, please do not modify and save, otherwise the contents will be permanently lost！
  - You can try using XMind 8 Update 3 or later version to open
- 该文件无法正常打开，请勿修改并保存，否则文件内容将会永久性丢失！
  - 你可以尝试使用 XMind 8 Update 3 或更新版本打开
- 該文件無法正常打開，請勿修改並保存，否則文件內容將會永久性丟失！
  - 你可以嘗試使用 XMind 8 Update 3 或更新版本打開
- この文書は正常に開かないので、修正して保存しないようにしてください。そうでないと、書類の内容が永久に失われます。！
  - XMind 8 Update 3 や更新版を使って開くこともできます
- Datei kann nicht richtig geöffnet werden. Bitte ändern Sie diese Datei nicht und speichern Sie sie, sonst wird die Datei endgültig gelöscht werden.
  - Bitte versuchen Sie, diese Datei mit XMind 8 Update 3 oder später zu öffnen.
- Ce fichier ne peut pas ouvert normalement, veuillez le rédiger et sauvegarder, sinon le fichier sera perdu en permanence. 
  - Vous pouvez essayer d'ouvrir avec XMind 8 Update 3 ou avec une version plus récente.
- 파일을 정상적으로 열 수 없으며, 수정 및 저장하지 마십시오. 그렇지 않으면 파일의 내용이 영구적으로 손실됩니다!
  - XMind 8 Update 3 또는 이후 버전을 사용하여
